name = "liubang"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Whether you are an antelope or a lion, you ought to dash forward without hesitation when the sun rise"
company = 'Baidu'
location = "China"

[social]
  github = "liubang"
  email = "it.liubang@gmail.com"
  qq = "1301841042"
  weibo = "2113750192"
