baseURL = "https://iliubang.cn"
title = "liubang's blog"
theme = "github.com/razonyang/hugo-theme-bootstrap"
copyright = "Copyright © 2016-{year} LiuBang. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
disableLanguages = ["fr", "zh-tw"]

# Pagination
[pagination]
  pagerSize = 10

paginatePath = "page"

enableRobotsTXT = true

enableEmoji = true

enableGitInfo = true

hasCJKLanguage = true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

timeout = "120s"

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS"]

# 分类
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[build]
  writeStats = true

[security.funcs]
  getenv = ['^HUGO_', '^CI$', 'PWD']
