baseURL = "https://iliubang.cn"
title = "liubang's blog"
theme = "github.com/razonyang/hugo-theme-bootstrap" 
copyright = "Copyright © 2016-{year} LiuBang. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true 
disableLanguages = ["fr", "zh-tw"] 

# Pagination
paginate = 10
paginatePath = "page"

enableRobotsTXT = true

enableEmoji = true

hasCJKLanguage = true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["json"]
  
[outputFormats]
  [outputFormats.MANIFEST]
    name = "manifest"
    baseName = "manifest"
    mediaType = "application/manifest+json"

[outputs]
  home = ["HTML", "RSS", "JSON", "MANIFEST"]

# 分类
[taxonomies]
  # category = "categories"
  # series = "series"
  tag = "tags"

[build]
  writeStats = true
