[zh-cn]
  languageName = "简体中文"
  weight = 4
  [zh-cn.params]
    dateFormat = "2006-01-02"
    description = "这是刘邦的blog"
    keywords = "blog,博客"
    [zh-cn.params.archive]
      dateFormat = "01-02"

[en]
  languageName = "English"
  weight = 1
