# [[main]]
#   name = "Support"
#   identifier = "support"
#   weight = 40
#   pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
# [[main]]
#   name = "Repository"
#   identifier = "repository"
#   parent = "support"
#   url = ""
#   weight = 1
# [[main]]
#   name = "Discussions"
#   identifier = "discussions"
#   parent = "support"
#   url = ""
#   weight = 2
# [[main]]
#   name = "Features Request"
#   identifier = "feature-request"
#   parent = "support"
#   url = ""
#   weight = 3
# [[main]]
#   parent = "support"
#   weight = 4
#   [main.params]
#     divider = true

# [[footer]]
#   name = "Support"
#   identifier = "support"
#   weight = 1
# [[footer]]
#   name = "Repository"
#   identifier = "repository"
#   parent = "support"
#   url = ""
#   weight = 1
#   pre = '<i class="fab fa-fw fa-github"></i>'
# [[footer]]
#   name = "Discussions"
#   identifier = "discussions"
#   parent = "support"
#   url = ""
#   weight = 2
#   pre = '<i class="fas fa-fw fa-comments"></i>'
# [[footer]]
#   name = "Features Request"
#   identifier = "feature-request"
#   parent = "support"
#   url = ""
#   weight = 3
# [[footer]]
#   name = "Bug Report"
#   identifier = "bug-report"
#   parent = "support"
#   url = ""
#   weight = 4
#
# [[footer]]
#   name = "Docs"
#   identifier = "docs"
#   weight = 2
#
# [[footer]]
#   name = "Features"
#   identifier = "features"
#   weight = 3

# [[footer]]
#   identifier = "demo"
#   name = "Demo"
#   weight = 4
# [[footer]]
#   identifier = "demo-netlify"
#   parent = "demo"
#   name = "Netlify"
#   weight = 1
#   url = ""
# [[footer]]
#   identifier = "demo-name"
#   parent = "demo"
#   name = "China"
#   weight = 2
#   url = ""
